create table public.trading (
  id bigint generated by default as identity not null,
  entry_date date not null,
  exit_date date null,
  options_trading_amount bigint null,
  required_profit bigint null,
  interest bigint null,
  actual_profit bigint null,
  total_profit bigint null,
  percent real null,
  mf_trading_amount bigint null,
  pnl bigint null,
  mf_profit real null,
  constraint trading_pkey primary key (id)
) TABLESPACE pg_default;